"""Модуль для хранения констант приложения."""

MAX_LENGTH_SHORT = 20
MAX_LENGTH_MIDDLE = 100
MAX_LENGTH_LONG = 200

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 1440

MIN_INGREDIENTS = 1
MAX_INGREDIENTS = 10000
