version: '3.8'

volumes:
  pg_data:
  static:  # Общая директория для статики
  media:   # Общая директория для медиа

services:
  db:
    image: postgres:13.10
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: romankrasowski/foodgram_backend
    container_name: foodgram_backend
    env_file: .env
    volumes:
      - static:/app/collected_static  # Подключаем STATIC_ROOT из settings.py
      - media:/app/media              # Подключаем MEDIA_ROOT из settings.py
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000"

  frontend:
    image: romankrasowski/foodgram_frontend
    container_name: foodgram_frontend
    env_file: .env
    volumes:
      - static:/static  # Общая директория для статики
    depends_on:
      - backend
    command: cp -r /app/build/. /static/

  gateway:
    image: romankrasowski/foodgram_gateway
    container_name: foodgram_gateway
    env_file: .env
    volumes:
      - static:/static/  # Подключаем статику для Nginx
      - media:/app/media/  # Подключаем медиа для Nginx
    depends_on:
      - backend
      - frontend
    ports:
      - "80:80"
