version: '3.3'

volumes:
  pg_data:
  static:
  media:
  docs:

services:
  db:
    image: postgres:13.10
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    container_name: foodgram_backend
    image: romankrasowski/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
      - docs:/docs
    depends_on:
      - db

  frontend:
    container_name: foodgram_frontend
    image: romankrasowski/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
    depends_on:
      - backend

  gateway:
    container_name: foodgram_gateway
    image: romankrasowski/foodgram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
      - docs:/usr/share/nginx/html/api/docs
    ports:
      - 10000:80
    depends_on:
      - backend
      - frontend
