volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    container_name: foodgram_db
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: romankrasowski/foodgram_backend
    container_name: backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
    depends_on:
      - db
    command: >
      bash -c "
      python manage.py collectstatic --noinput &&
      python manage.py migrate &&
      gunicorn foodgram.wsgi:application --bind 0.0.0.0:8000
      "

  frontend:
    image: romankrasowski/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    image: romankrasowski/foodgram_gateway
    env_file: .env
    volumes:
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
      - frontend
    ports:
      - "10000:80"
