server {
  listen 80;
  server_tokens off;

  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/api/;
  }

  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/admin/;
  }

  location /media/ {
    alias /media/;
    autoindex on;
  }

  location / {
      alias /staticfiles/;
      proxy_set_header Host $http_host;
      try_files $uri $uri/ /index.html;
  }

  location /s/ {
    proxy_pass http://backend:9000/s/;
    proxy_set_header Host $http_host;
  }
}
