# Generated by Django 4.2.16 on 2024-10-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20241006_2341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'verbose_name': 'Подписки', 'verbose_name_plural': 'Подписки'},
        ),
        migrations.AlterModelOptions(
            name='ingredientrecipe',
            options={'verbose_name': 'Ингридиенты рецепта', 'verbose_name_plural': 'Ингридиенты рецепта'},
        ),
        migrations.AlterField(
            model_name='recipe',
            name='picture',
            field=models.ImageField(help_text='Добавьте фото рецепта.', upload_to='media/', verbose_name='Фото рецепта'),
        ),
    ]
