# Generated by Django 4.2.18 on 2025-01-26 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profiles', verbose_name='Аватар пользователя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(code='invalid', message='Введите корректное имя пользователя.Допустимы только буквы, цифры и символы @/./+/-/_', regex='^[\\w.@+-]+$')], verbose_name='Логин пользователя'),
        ),
    ]
